name: Seed db Workflow
on: workflow_dispatch

env:
  image: 'eliasm50/techchallengeapp:latest'
  AZURE_WEBAPP_NAME: chappweb   # Azure App Service Name 

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true            

      - name: Deploy CI
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}-ci-app
          images: ${{ env.image }}
          startup-command: seeddb

      # Azure logout
      - name: logout
        run: |
          az logout