name: Seed db Workflow
on: workflow_dispatch

env:
  imageTag: '1.0.${{ github.run_number }}'
  AZURE_WEBAPP_NAME: chappweb   # Azure App Service Name 
  CONTAINER_REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true            

      - name: Deploy CI
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}-ci-app
          images: eliasm50/techchallengeapp:latest
          startup-command: seeddb

      # Azure logout
      - name: logout
        run: |
          az logout